### ISSUE TITLE
Font Awesome 5

### ISSUE THREAD

**Issue by BassWindoo** [LexaGV/WPFColorLib#1]
Hello ;),

Do you have a link to the "Font Awesome 5 Free Regular" you use in your color piker ?

I tryed many but no one match.

Thx.

**Comment by LexaGV** [comment]
DL page: https://fontawesome.com/v5/download
Exact link: https://use.fontawesome.com/releases/v5.15.4/fontawesome-free-5.15.4-desktop.zip

Good luck!
I updated README with font link, thanks you asked! :)
